[ -f ~/.cargo/env ] && . ~/.cargo/env
export PATH=$PATH:/usr/local/go/bin
export NVM_DIR="$HOME/.nvm"

# Load functions
fpath=(~/.zsh/functions $fpath)

# Required for FZF
autoload -Uz ${fpath[1]}/*(:t)
