[ -f ~/.zsh/aliases ] && source ~/.zsh/aliases
[ -f ~/.zsh/bindings ] && source ~/.zsh/bindings
[ -f ~/.zsh/tokens ] && source ~/.zsh/tokens
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# UI themes
[ -f ~/.zsh/themes/p10k.zsh ] && source ~/.zsh/themes/p10k.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion

# Work directories --- Used by utility functions
export ZSH_WORK_DIRS=~/workspace:~/personal:~/workspace/live_revenue_monorepo/packages/apps:~/go/src/code.byted.org/jameszhang:~/workspace/live_revenue_monorepo/packages/libs:~/workspace/live_revenue_monorepo/packages/apps/tiktok_live_lynx/revenue:~/workspace/live_revenue_monorepo/packages/libs/tiktok_live_lynx/sab:~/workspace/live_revenue_monorepo/packages/apps/tiktok_live_h5/revenue:~/workspace/live_revenue_monorepo/subspaces

source ~/powerlevel10k/powerlevel10k.zsh-theme
export PATH="/usr/local/bin:/opt/homebrew/opt/curl/bin:$PATH"
export XDG_CONFIG_HOME="$HOME/.config"



# --- BEGIN FEDERATED REPO GIT TELEMETRY CODE BLOCK ---
# https://bytedance.sg.larkoffice.com/docx/SurId67UBoZxHwxe07Clr5Ufgog

export FEDERATED_REPO_GIT_TELEMETRY_VERSION=1.3.0
export GIT_TRACE2_EVENT="$HOME/.trace2/event"
export GIT_TRACE2_EVENT_BRIEF=true
export GIT_TRACE2_MAX_FILES=100000

# --- END FEDERATED REPO GIT TELEMETRY CODE BLOCK ---


